# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(help_text='Is the device a Node, Relay or Coordinator?', max_length=2, verbose_name='Device Type')),
                ('digi_profile_id', models.CharField(help_text='A number representing a particular communication type, see Digi documentation', max_length=4, verbose_name='Digi Profile ID')),
                ('manufacturer_id', models.CharField(help_text='The number identifying the device manufacturer', max_length=4, verbose_name='Manufacturer')),
                ('node_id', models.CharField(help_text='The name given to the node', max_length=60, verbose_name='Node ID')),
                ('options', models.CharField(help_text='Bit-coded field of options for packet delivery #FIXME find reference', max_length=2, verbose_name='Options')),
                ('packet_type', models.CharField(help_text='The purpose of this packet', max_length=60, verbose_name='Packet Type')),
                ('parent_source_addr', models.CharField(help_text='#FIXME', max_length=4, verbose_name='Parent Soruce Address')),
                ('sender_addr', models.CharField(help_text="Short version of sender's address (node which relayed packet to coordinator)", max_length=4, verbose_name='Sender Address')),
                ('sender_addr_long', models.CharField(help_text='Long form address of the node which relayed the packet to coordinator', max_length=16, verbose_name='Sender Address (Long)')),
                ('source_addr', models.CharField(help_text='Short version of source address (original source)', max_length=4, verbose_name='Source Address')),
                ('source_addr_long', models.CharField(help_text='Long form address of original source of packet', max_length=16, verbose_name='Source Address (Long)')),
                ('source_event', models.CharField(help_text='TODO: what is source event?', max_length=2, verbose_name='Source Event')),
                ('timestamp', models.CharField(help_text='The time at which this packet was received from the coordinator node', max_length=15, verbose_name='Received')),
                ('stuff', models.CharField(help_text='#FIXME', max_length=8, verbose_name='FIXME')),
            ],
        ),
        migrations.CreateModel(
            name='RfData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(help_text='Bit-coded field of options for packet delivery #FIXME find reference', max_length=2, verbose_name='Options')),
                ('packet_type', models.CharField(help_text='The purpose of this packet', max_length=60, verbose_name='Packet Type')),
                ('rf_data', models.CharField(help_text='The data sent from the source', max_length=255, verbose_name='RF Data')),
                ('source_addr', models.CharField(help_text='Short version of source address', max_length=4, verbose_name='Source Address')),
                ('source_addr_long', models.CharField(help_text='Long form address of original source of packet', max_length=16, verbose_name='Source Address (Long)')),
                ('timestamp', models.CharField(help_text='The time at which this packet was received from the coordinator node', max_length=15, verbose_name='Received')),
            ],
        ),
    ]
